CREATE DATABASE MULTI_TABLA
USE MULTI_TABLA

CREATE TABLE COLOR
(ID_COLOR INT IDENTITY(1,1) PRIMARY KEY,
COLOR_FAVORITO VARCHAR(20)NOT NULL)

CREATE TABLE COMIDA
(ID_COMIDA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_COM VARCHAR(20)NOT NULL)

CREATE TABLE EQUIPO
(ID_EQUIPO INT IDENTITY(1,1)PRIMARY KEY,
NOMBRE_EQ VARCHAR(20)NOT NULL)

CREATE TABLE PERSONA
(ID_PERSONA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_P VARCHAR (50)NOT NULL,
ID_EQ INT REFERENCES EQUIPO(ID_EQUIPO)NOT NULL,
ID_COL INT REFERENCES COLOR(ID_COLOR)NOT NULL,
ID_CO INT REFERENCES COMIDA(ID_COMIDA)NOT NULL)


SELECT*FROM COLOR

INSERT INTO COLOR VALUES ('AMARILLO')
INSERT INTO COLOR VALUES ('ROSADO')
INSERT INTO COLOR VALUES ('MORADO')
INSERT INTO COLOR VALUES ('AZUL')
INSERT INTO COLOR VALUES ('VERDE')
INSERT INTO COLOR VALUES ('GRIS')

SELECT*FROM COMIDA

INSERT INTO COMIDA VALUES ('PIZZA')
INSERT INTO COMIDA VALUES ('PERRO')
INSERT INTO COMIDA VALUES ('POLLO')
INSERT INTO COMIDA VALUES ('HAMBURGUESA')
INSERT INTO COMIDA VALUES ('SALCHIPAPAS')
INSERT INTO COMIDA VALUES ('PICADA')

SELECT*FROM EQUIPO

INSERT INTO EQUIPO VALUES ('NACIONAL')
INSERT INTO EQUIPO VALUES ('MEDELLIN')
INSERT INTO EQUIPO VALUES ('MILLONARIOS')
INSERT INTO EQUIPO VALUES ('ENVIGADO')
INSERT INTO EQUIPO VALUES ('AMERICA')
INSERT INTO EQUIPO VALUES ('ALIANZA')

SELECT*FROM PERSONA

INSERT INTO PERSONA VALUES ('VALERIA', 1,3,5)
INSERT INTO PERSONA VALUES ('CRISTIAN', 4,2,1)
INSERT INTO PERSONA VALUES ('DIANA',5,4,3)
INSERT INTO PERSONA VALUES ('MARIA',1,2,3)
INSERT INTO PERSONA VALUES ('JOSE',2,3,4)
INSERT INTO PERSONA VALUES ('VALENTINA',6,2,1)


SELECT * FROM EQUIPO
SELECT * FROM COLOR
SELECT * FROM PERSONA

SELECT TOP 2*FROM PERSONA

SELECT*FROM PERSONA WHERE NOMBRE_P LIKE 'V%'

SELECT NOMBRE_P,NOMBRE_COM FROM PERSONA JOIN COMIDA ON PERSONA.ID_CO=COMIDA.ID_COMIDA

SELECT NOMBRE_P, NOMBRE_EQ FROM PERSONA JOIN EQUIPO ON PERSONA.ID_EQ=EQUIPO.ID_EQUIPO

SELECT*FROM PERSONA FULL OUTER JOIN EQUIPO ON PERSONA.ID_EQ=EQUIPO.ID_EQUIPO FULL OUTER JOIN COLOR ON PERSONA.ID_COL=COLOR.ID_COLOR

SELECT NOMBRE_P, COLOR_FAVORITO FROM PERSONA RIGHT JOIN COLOR ON PERSONA.ID_COL=COLOR.ID_COLOR ORDER BY PERSONA.ID_PERSONA

SELECT ID_PERSONA, NOMBRE_P, ID_EQUIPO, NOMBRE_EQ FROM PERSONA P 
INNER JOIN EQUIPO E ON P.ID_EQ = E.ID_EQUIPO

SELECT ID_PERSONA, NOMBRE_P, ID_EQUIPO, NOMBRE_EQ FROM PERSONA P
LEFT OUTER JOIN EQUIPO E ON P.ID_EQ = E.ID_EQUIPO

SELECT ID_PERSONA, NOMBRE_P, ID_EQUIPO, NOMBRE_EQ FROM PERSONA P 
RIGHT OUTER JOIN EQUIPO E ON P.ID_EQ = E.ID_EQUIPO

SELECT * FROM PERSONA P WHERE EXISTS (SELECT 1 FROM EQUIPO E WHERE P.ID_EQ = E.ID_EQUIPO)

SELECT * FROM PERSONA P WHERE NOT EXISTS (SELECT 1 FROM EQUIPO E WHERE P.ID_EQ = E.ID_EQUIPO)

SELECT * FROM PERSONA P 
LEFT OUTER JOIN EQUIPO E ON P.ID_EQ = E.ID_EQUIPO WHERE E.ID_EQUIPO IS NULL

SELECT * FROM PERSONA P RIGHT OUTER JOIN EQUIPO E ON P.ID_EQ = E.ID_EQUIPO WHERE P.ID_EQ IS NULL

SELECT * FROM PERSONA P FULL OUTER JOIN EQUIPO E ON P.ID_EQ = E.ID_EQUIPO

SELECT * FROM PERSONA P CROSS JOIN EQUIPO E

SELECT * FROM PERSONA P CROSS JOIN COLOR C

SELECT * FROM PERSONA P FULL OUTER JOIN EQUIPO E ON P.ID_EQ = E.ID_EQUIPO
WHERE P.ID_EQ IS NULL OR E.ID_EQUIPO IS NULL

SELECT * FROM PERSONA P INNER JOIN EQUIPO E ON P.ID_EQ >= E.ID_EQUIPO

SELECT ID_PERSONA, NOMBRE_P, ID_EQUIPO, NOMBRE_EQ, ID_COLOR, COLOR_FAVORITO FROM PERSONA P
FULL OUTER JOIN EQUIPO E ON P.ID_EQ = E.ID_EQUIPO 
FULL OUTER JOIN COLOR C ON P.ID_COL = C.ID_COLOR

SELECT ID_PERSONA, NOMBRE_P, ID_EQ, NOMBRE_EQ,
ID_COLOR, COLOR_FAVORITO FROM PERSONA P
INNER JOIN EQUIPO E ON P.ID_EQ = E.ID_EQUIPO 
INNER JOIN COLOR C ON P.ID_COL = C.ID_COLOR

SELECT * FROM PERSONA P 
LEFT OUTER JOIN EQUIPO E ON P.ID_EQ = E.ID_EQUIPO
LEFT OUTER JOIN COLOR C ON P.ID_COL = C.ID_COLOR

SELECT * FROM PERSONA P
INNER JOIN EQUIPO E ON P.ID_EQ = E.ID_EQUIPO
LEFT OUTER JOIN COLOR C ON P.ID_COL = C.ID_COLOR

SELECT ID_COL as id FROM PERSONA UNION SELECT ID_COLOR FROM COLOR

SELECT ID_EQ as id FROM PERSONA INTERSECT SELECT ID_EQUIPO FROM EQUIPO

-- VISTAS
--1
CREATE VIEW V_DATOS_PERSONA 
AS
SELECT NOMBRE_P, COLOR_FAVORITO FROM PERSONA JOIN COLOR ON PERSONA.ID_COL=COLOR.ID_COLOR

SELECT * FROM V_DATOS_PERSONA

--2
CREATE VIEW V_COMIDA_VALE 
AS
SELECT NOMBRE_P, NOMBRE_COM FROM PERSONA JOIN COMIDA ON PERSONA.ID_CO=COMIDA.ID_COMIDA WHERE NOMBRE_P='VALENTINA'

SELECT*FROM V_COMIDA_VALE

--3
CREATE VIEW V_DATOS_EQUIPO
AS
SELECT ID_PERSONA, NOMBRE_EQ FROM PERSONA JOIN EQUIPO ON PERSONA.ID_EQ=EQUIPO.ID_EQUIPO 

SELECT*FROM V_DATOS_EQUIPO

--4
CREATE VIEW V_EQUIPO_VALERIA
AS
SELECT ID_PERSONA, NOMBRE_EQ FROM PERSONA JOIN EQUIPO ON PERSONA.ID_EQ=EQUIPO.ID_EQUIPO WHERE ID_PERSONA=1

SELECT*FROM V_EQUIPO_VALERIA

--5
CREATE VIEW V_TODOS
AS
SELECT NOMBRE_P, NOMBRE_EQ, NOMBRE_COM, COLOR_FAVORITO 
FROM PERSONA JOIN EQUIPO ON PERSONA.ID_EQ=EQUIPO.ID_EQUIPO
JOIN COMIDA ON PERSONA.ID_CO=COMIDA.ID_COMIDA
JOIN COLOR ON PERSONA.ID_COL=COLOR.ID_COLOR

SELECT*FROM V_TODOS

--6
CREATE VIEW V_NOM_EQU
AS
SELECT NOMBRE_P,NOMBRE_EQ FROM PERSONA JOIN EQUIPO ON PERSONA.ID_EQ=EQUIPO.ID_EQUIPO WHERE NOMBRE_EQ='NACIONAL'

SELECT*FROM V_NOM_EQU

--7
CREATE VIEW V_TODAS_JUNTAS
AS
SELECT*FROM PERSONA JOIN EQUIPO ON PERSONA.ID_EQ=EQUIPO.ID_EQUIPO
JOIN COMIDA ON PERSONA.ID_CO=COMIDA.ID_COMIDA
JOIN COLOR ON PERSONA.ID_COL=COLOR.ID_COLOR

SELECT*FROM V_TODAS_JUNTAS

--8
CREATE VIEW V_ID
AS
SELECT ID_PERSONA, ID_EQUIPO,ID_COMIDA,ID_COLOR FROM PERSONA JOIN EQUIPO ON PERSONA.ID_EQ=EQUIPO.ID_EQUIPO
JOIN COMIDA ON PERSONA.ID_CO=COMIDA.ID_COMIDA
JOIN COLOR ON PERSONA.ID_COL=COLOR.ID_COLOR

SELECT*FROM V_ID

--9
CREATE VIEW VISTA_ENCR
WITH ENCRYPTION
AS
SELECT ID_PERSONA,NOMBRE_COM FROM PERSONA JOIN COMIDA ON PERSONA.ID_CO=COMIDA.ID_COMIDA

SELECT*FROM VISTA_ENCR
EXEC SP_HELPTEXT VISTA_ENCR

--10
CREATE VIEW VIST
AS
SELECT*FROM PERSONA CROSS JOIN COMIDA

SELECT*FROM VIST

--11
CREATE VIEW VIS
AS
SELECT * FROM PERSONA WHERE NOMBRE_P LIKE 'V%'

SELECT*FROM VIS

